"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {ExperienceDefinition,ExperienceChoice} from "./model";
import {useExperienceSession} from "./use-experience-session";
import "./experience-runtime.css";
export function ExperienceRuntime({definition,presentationGrammarId}:{definition:ExperienceDefinition;presentationGrammarId?:string}){
 const scenes=useMemo(()=>new Map(definition.sceneGraph.scenes.map(s=>[s.id,s])),[definition]);const session=useExperienceSession({experienceId:definition.experienceId,entrySceneId:definition.sceneGraph.entrySceneId,statePolicy:definition.runtimeStatePolicy});const [selected,setSelected]=useState("");const headingRef=useRef<HTMLHeadingElement>(null);const scene=scenes.get(session.currentSceneId)??scenes.get(definition.sceneGraph.entrySceneId);
 useEffect(()=>{setSelected("");headingRef.current?.focus();},[session.currentSceneId]);
 if(!session.ready||!scene)return <main className="experienceRuntime"><p>Preparazione esperienza…</p></main>;
 if(session.completion.status==="completed"||scene.terminal||scene.interaction.kind==="terminal")return <main className="experienceRuntime"><article className="experienceScene"><h1 ref={headingRef} tabIndex={-1}>{scene.title||"Completed"}</h1>{scene.body?.map((p,i)=><p key={i}>{p}</p>)}<div role="status" aria-live="polite">{session.lastFeedback}</div><button type="button" onClick={session.restart}>Restart</button></article></main>;
 const choices=scene.interaction.choices||[];const chosen=choices.find(c=>c.id===selected);const choose=(choice:ExperienceChoice)=>{setSelected(choice.id);session.writeResponse(scene.id,choice.id);};const continueFlow=()=>{if(!chosen)return;const target=scenes.get(chosen.targetSceneId);if(!target)return;session.proceed(target.id,chosen.feedback?.text||"",Boolean(target.terminal||target.interaction.kind==="terminal"));};
 return <main className="experienceRuntime" data-presentation-grammar={presentationGrammarId||definition.presentationGrammarRef}><article className="experienceScene"><p className="experiencePrimitive">{scene.primitive}</p><h1 ref={headingRef} tabIndex={-1}>{scene.title||scene.id}</h1>{scene.body?.map((p,i)=><p key={i}>{p}</p>)}{scene.interaction.kind==="choice"&&<fieldset><legend>{scene.interaction.prompt||"Choose"}</legend><div className="experienceChoices">{choices.map(choice=><label key={choice.id}><input type="radio" name={scene.id} value={choice.id} checked={selected===choice.id} onChange={()=>choose(choice)}/><span>{choice.label}</span></label>)}</div></fieldset>}<div className="experienceFeedback" role="status" aria-live="polite">{selected&&chosen?.feedback?.text?chosen.feedback.text:session.lastFeedback}</div><button type="button" disabled={!selected} onClick={continueFlow}>Continue</button></article></main>;
}
