export type PresentationCondition = "N" | "L";

export type PathwaySceneId =
  | "S1_ORIENT"
  | "S2_MISSING_INFO"
  | "S3_CHOOSE_PROCESS"
  | "S4_CONSEQUENCE"
  | "S5_REVISE"
  | "S6_NAME_STRATEGY"
  | "S7_CHANGED_CONTEXT"
  | "S8_TRANSFER_PROBE"
  | "S9_TRACE_CONTROL";

export type PathwayOption = { id: string; label: string };
export type PathwayScene = { id: PathwaySceneId; title: string; prompt: string; facts: string[]; options: PathwayOption[]; feedback: Record<string, string> };

export const pathwayScenes: PathwayScene[] = [
  { id: "S1_ORIENT", title: "Una decisione da prendere", prompt: "Osserva la situazione. Che cosa sta succedendo?", facts: ["Un gruppo deve scegliere come organizzare un'attività.", "Non tutte le informazioni sono ancora disponibili."], options: [{ id: "continue", label: "Osservo i fatti" }], feedback: { continue: "Partiamo da ciò che sappiamo, senza aggiungere informazioni che non abbiamo." } },
  { id: "S2_MISSING_INFO", title: "Che cosa manca?", prompt: "Prima di decidere, quale informazione manca?", facts: ["Il gruppo conosce l'obiettivo dell'attività.", "Non sa ancora quali risorse siano effettivamente disponibili."], options: [{ id: "resources", label: "Quali risorse sono disponibili" }, { id: "fast", label: "Chi decide più velocemente" }, { id: "popular", label: "Quale scelta sembra più popolare" }], feedback: { resources: "Questa informazione permette di confrontare le possibilità con un dato che manca.", fast: "La velocità della decisione non chiarisce quali risorse siano disponibili.", popular: "La popolarità non aggiunge il dato che manca alla situazione." } },
  { id: "S3_CHOOSE_PROCESS", title: "Come decidere?", prompt: "Quale modo di decidere vuoi provare?", facts: ["Possiamo scegliere subito oppure cercare prima il dato mancante."], options: [{ id: "a", label: "Scegliere subito con i dati presenti" }, { id: "b", label: "Controllare prima le risorse disponibili" }, { id: "c", label: "Seguire l'idea scelta da più persone" }], feedback: { a: "Il gruppo può decidere subito, ma l'informazione sulle risorse resta sconosciuta.", b: "Il gruppo aggiunge un'informazione pertinente prima di decidere.", c: "Il gruppo conosce una preferenza, ma non ha ancora verificato le risorse." } },
  { id: "S4_CONSEQUENCE", title: "Osserva la conseguenza", prompt: "Che cosa cambia dopo questa scelta?", facts: ["Ogni processo rende disponibili informazioni diverse prima della decisione."], options: [{ id: "inspect", label: "Confronto ciò che sappiamo prima e dopo" }], feedback: { inspect: "Una conseguenza utile da osservare è se il dato necessario è diventato disponibile oppure no." } },
  { id: "S5_REVISE", title: "Puoi rivedere la scelta", prompt: "Vuoi tenere questa scelta o provarne un’altra?", facts: ["Rivedere una scelta non comporta penalità."], options: [{ id: "keep", label: "Tengo la scelta" }, { id: "revise", label: "Provo un altro modo" }], feedback: { keep: "Puoi continuare e osservare che cosa permette di sapere questa scelta.", revise: "Puoi cambiare strategia alla luce di ciò che hai osservato." } },
  { id: "S6_NAME_STRATEGY", title: "Diamo un nome alla strategia", prompt: "Quale strategia aiuta a controllare ciò che mancava?", facts: ["Una strategia può essere descritta senza giudicare la persona che la usa."], options: [{ id: "check", label: "Individuare il dato mancante e controllarlo prima di decidere" }, { id: "guess", label: "Indovinare il dato mancante" }], feedback: { check: "La strategia collega la decisione a un'informazione pertinente da verificare.", guess: "Indovinare non rende disponibile l'informazione mancante." } },
  { id: "S7_CHANGED_CONTEXT", title: "Una situazione diversa", prompt: "La stessa strategia può servire anche qui?", facts: ["Una classe deve scegliere un materiale per un laboratorio.", "Non è ancora noto quali materiali siano già disponibili."], options: [{ id: "yes", label: "Sì: prima controllo ciò che è disponibile" }, { id: "no", label: "No: scelgo senza controllare" }], feedback: { yes: "La superficie della situazione cambia, ma anche qui manca un'informazione pertinente.", no: "Scegliere senza controllare lascia ancora sconosciuto un dato utile alla decisione." } },
  { id: "S8_TRANSFER_PROBE", title: "Controllare una fonte", prompt: "Prima di decidere, che cosa conviene controllare?", facts: ["Due fonti riportano informazioni diverse sullo stesso argomento."], options: [{ id: "evidence", label: "Quali prove e fonti sostengono le informazioni" }, { id: "layout", label: "Quale pagina ha l'aspetto più gradevole" }, { id: "first", label: "Quale informazione ho letto per prima" }], feedback: { evidence: "Controllare prove e provenienza aggiunge informazioni pertinenti per valutare le fonti.", layout: "L'aspetto della pagina non risolve la differenza tra le informazioni.", first: "L'ordine di lettura non verifica quale informazione sia sostenuta meglio." } },
  { id: "S9_TRACE_CONTROL", title: "La strategia resta tua", prompt: "In una versione futura autorizzata, come preferiresti gestire una traccia locale della strategia?", facts: ["Questa è soltanto una simulazione: in questo prototipo non viene salvato nulla sul dispositivo.", "Nessuna risposta viene inviata ad Atlas."], options: [{ id: "keep-local", label: "Simulerei: conserva sul dispositivo" }, { id: "discard", label: "Simulerei: non conservare" }], feedback: { "keep-local": "Scelta simulata. In questo prototipo non viene scritto alcun dato sul dispositivo.", discard: "Scelta simulata. La sessione non conserva alcuna traccia." } },
];
